# Generated by Django 5.0 on 2023-12-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('notstarted', 'notstarted'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='notstarted', max_length=20)),
            ],
        ),
    ]
