# Generated by Django 5.0 on 2023-12-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobe',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tobe',
            name='status',
            field=models.CharField(choices=[('notstarted', 'notstarted'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='notstarted', max_length=30),
        ),
    ]
